const ACTIONS={
    JOIN_ROOM:"join-room",
    GET_ONLINE_USERS:"getOnlineUsers",
    USER_JOINED:"user-joined",
    FILE_CREATED:"file-created",
    FILE_DELETED:"file-deleted",
    FOLDER_CREATED:"folder-created",
    FOLDER_DELETED:"folder-deleted",
    RECEIVE_FILE_CREATED:"receive-file-created",
    RECEIVE_FOLDER_CREATED:"receive-folder-created",
    RECEIVE_NODE_DELETED:"receive-node-deleted",
    FILE_UPDATED:"file-updated",
    RECEIVE_FILE_UPDATED:"receive-file-updated",
    SEND_MESSAGE:"send-message",
    RECEIVE_MESSAGE:"receive-message",
    DOC_JOIN:"doc:join",
    DOC_SYNC:"doc:sync",
    DOC_UPDATE:"doc:update",
    DOC_AWARENESS:"doc:awareness",
    DOC_ERROR:"doc:error",
    DOC_LEAVE:"doc:leave",
    LEAVE_ROOM:"leave-room",
    USER_LEFT:"user-left"
}
export default ACTIONS;